# Generated by Django 3.1.2 on 2023-02-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categoory',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'mobile'), ('L', 'laptop'), ('TW', 'topwear'), ('BW', 'bottomwear')], default=2, max_length=50),
            preserve_default=False,
        ),
    ]
